[package]
name = "quamatic/floating-ui"
description = "Floating elements implementation for React"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["src", "src/*", "wally.toml", "LICENSE", "README.md", "default.project.json"]

[dependencies]
React = "core-packages/react@17.0.1-rc.19"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.19"
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.3"
Promise = "evaera/promise@^4"